package eulerproject.level4.problem84;

import org.junit.Test;

/**
 * Created by Lukasz on 2017-05-28.
 */
public class ChanceCardsTest {


    @Test
    public void getNext() throws Exception {

        ChanceCards chanceCards = new ChanceCards();

        System.out.println(chanceCards.getNext());
        System.out.println(chanceCards.getNext());
        System.out.println(chanceCards.getNext());
        System.out.println(chanceCards.getNext());
        System.out.println(chanceCards.getNext());
        System.out.println(chanceCards.getNext());
        System.out.println(chanceCards.getNext());
        System.out.println(chanceCards.getNext());
        System.out.println(chanceCards.getNext());
        System.out.println(chanceCards.getNext());
        System.out.println(chanceCards.getNext());
        System.out.println(chanceCards.getNext());
        System.out.println(chanceCards.getNext());
        System.out.println(chanceCards.getNext());
        System.out.println(chanceCards.getNext());
        System.out.println(chanceCards.getNext());
        System.out.println(chanceCards.getNext());
        System.out.println(chanceCards.getNext());
        System.out.println(chanceCards.getNext());
        System.out.println(chanceCards.getNext());
        System.out.println(chanceCards.getNext());
        System.out.println(chanceCards.getNext());
        System.out.println(chanceCards.getNext());
    }

}